swagger: "2.0"
info:
  title: payment-management-b
  version: 1.0.0
  description: API que expone la generación de orden de transferencia interbancaria
basePath: /payment-management-b/v1
paths:
  /external-transfers/create:
    post:
      tags:
        - BQ - ExternalTransfers
      operationId: postExternalTransfers
      description: Expone la generación de orden de transferencia interbancaria
      summary: Expone la generación de orden de transferencia interbancaria
      produces:
        - application/json
      parameters:
        - name: channelIdentification
          in: header
          description: Indicador del canal
          required: true
          type: string
        - name: messageIdentification
          in: header
          description: Indicador del mensaje
          required: true
          type: string
        - name: body
          schema:
            $ref: >-
              #/definitions/REQUEST_CreateExternalTransfers
          in: body
          required: true
      responses:
        "200":
          schema:
            $ref: >-
              #/definitions/RESPONSE_CreateExternalTransfersResponse
          description: OK
        "204":
          description: No Content
        "400":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Bad Request
        "401":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Unauthorized
        "404":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Not Found
        "422":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Unprocessable Content
        "500":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Internal Server Error
        "502":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Bad Gateway
        "504":
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Gateway Timeout
definitions:
  errorResponse:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status_code:
              type: string
              description: Código de error
            message:
              type: string
              description: Mensaje de error
  REQUEST_CreateExternalTransfers:
    description: ""
    required:
      - CreateExternalTransfers
    type: object
    properties:
      CreateExternalTransfers:
        description: "Objeto que representa al request del mesnsaje"
        type: object
        properties:
          Debtor:
            type: object
            description: "Objeto que representa al debtor quien envia el dinero"
            properties:
              Account:
                type: object
                description: "Objeto que contiene la información de la dirección de la cuenta del deudor"
                properties:
                  CCIIdentification:
                    type: string
                    description: "Código de Cuenta Interbancario del Cliente Originante"
                    example: "1234011-0052-89-0001234567856789"
          Transaction:
            type: object
            description: Objeto que contiene la información de las transacciones
            properties:
              Amount:
                type: object
                properties:
                  Value:
                    type: number
                    description: Cantidad de dinero involucrada en la operación.
                    example: 510
              Commission:
                type: object
                properties:
                  Amount:
                    type: object
                    description: "Objeto que contiene la información de los montos de la comisión"
                    properties:
                      Value:
                        type: number
                        description: "Hace referencia al Importe de Comisión"
                        example: 10.00
          MoneyTransferInstruction:
            type: object
            description: Objeto que contiene la información del monto a tranferir
            properties:
              MoneyTransferInstructionAmount:
                type: object
                properties:
                  Value:
                    type: number
                    description: Monto total de la transferencia
                    example: 500
          CurrencyInternalIdentifier:
            type: integer
            description: Identificador interno de la caja
            example: 1
  RESPONSE_CreateExternalTransfersResponse:
    description: ""
    type: object
    properties:
      CreateExternalTransfersResponse:
        type: object
        description: Objeto que almacena el mensaje de respuesta
        properties:
          ResponseCode:
            type: string
            description: "Código de Respuesta del servicio"
            example: "00"
          InstructionIdentification:
            type: string
            description: "Autogenerado de identificación única de transacción"
            example: "5f1a4342e318e8f44cf59b48"
          MoneyTransferInstruction:
            type: object
            description: Objeto que contiene la información del monto a tranferir
            properties:
              MoneyTransferInstructionAmount:
                type: object
                properties:
                  Value:
                    type: number
                    description: Monto total de la transferencia
                    example: 500
