swagger: '2.0'
info:
  title: payment-initiation-s
  version: 1.0.0
  description: Consulta Transferencia por recurso información de cuenta Interbancaria CCI o número de teléfono
basePath: /payment-initiation-s/v1
paths:
  /external-transfers/retrieve:
    post:
      tags:
      - BQ - ExternalTransfers
      operationId: getExternalTransfers
      description: Consulta Transferencia por recurso información de cuenta Interbancaria CCI o número de teléfono
      summary: Consulta Transferencia por recurso información de cuenta Interbancaria CCI o número de teléfono
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: >-
              #/definitions/RESPONSE_RetrieveExternalTransfersResponse
          description: OK
        '204':
          description: No Content
        '400':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Bad Request
        '401':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Unauthorized
        '404':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Not Found
        '422':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Unprocessable Content
        '500':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Internal Server Error
        '502':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Bad Gateway
        '504':
          schema:
            $ref: >-
              #/definitions/errorResponse
          description: Gateway Timeout
      parameters:
        - name: channelIdentification
          in: header
          description: Indicador del canal
          required: true
          type: string
        - name: messageIdentification
          in: header
          description: Indicador del mensaje
          required: true
          type: string
        - name: body
          schema:
            $ref: >-
              #/definitions/REQUEST_RetrieveExternalTransfers
          in: body
          required: true
  /contact-sweep/retrieve:
    get:
      tags:
        - BQ - ContactSweep
      operationId: getSweep
      summary: Consulta de barrido
      description: Esta API permite revisar si el listado de números de contacto de un cliente se encuentra registrado en algún directorio de un servicio 
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RESPONSE_RetrieveContactSweepResponse'
        '204':
          description: No Content
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/errorResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/errorResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/errorResponse'
        '422':
          description: Unprocessable Content
          schema:
            $ref: '#/definitions/errorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorResponse'
        '502':
          description: Bad Gateway
          schema:
            $ref: '#/definitions/errorResponse'
        '504':
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/errorResponse'
      parameters:
        - name: channelIdentification
          in: header
          description: Indicador del canal
          required: true
          type: string
        - name: messageIdentification
          in: header
          description: Indicador del mensaje
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/REQUEST_RetrieveContactSweep'
definitions:
  errorResponse:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status_code:
              type: string
              description: Código de error
            message:
              type: string
              description: Mensaje de error
  REQUEST_RetrieveExternalTransfers:
    description: ''
    required:
      - RetrieveExternalTransfers
    type: object
    properties:
      RetrieveExternalTransfers:
        description: 'Objeto que representa al cuerpo de mensaje'
        properties:
          DebtorAgent:
            type: object
            description: 'Objeto que contiene la información del institución financiera del deudor'
            properties:
              FinancialInstitution:
                type: object
                description: 'Objeto que contiene la información de la institución financiera'
                properties:
                  Identification:
                    type: string
                    description: 'Código de la Entidad Originante '
                    example: '250000'
          Debtor:
            type: object
            description: 'Objeto que representa al debtor quien envia el dinero'
            properties:
              PersonName:
                type: object
                description: 'Objeto que representa al deudor'
                properties:
                  FullName:
                    type: string
                    description: 'Nombre del Cliente Originante'
                    example: 'Jane Doe'
              PersonIdentification:
                type: object
                description: 'Objeto que representa al deudor'
                properties:
                  PersonType:
                    type: string
                    description: 'Tipo de Persona del Cliente Originante'
                    example: '1'
                  TypeOfIdentification:
                    type: string
                    description: 'Tipo de Documento del Cliente Originante'
                    example: '1'
                  IdentityCardNumber:
                    type: string
                    description: ' Número de Documento del Cliente Originante'
                    example: 'Jhon Doe'
              Contact:
                type: object
                description: 'Objeto que contiene la información de contacto'
                properties:
                  PhoneNumber:
                    type: string
                    description: 'Número de teléfono fijo del Cliente Originante'
                    example: '97145847'
                  MobileNumber:
                    type: string
                    description: 'Número de celular del Cliente Originante'
                    example: '858885474'
              Location:
                type: object
                description: 'Dirección del Cliente Originante'
                properties:
                  Address:
                    type: string
                    description: 'Dirección del Cliente Originante'
                    example: 'Dirección'
          CreditorAgent:
            type: object
            description: 'Objeto que contiene la información del institución financiera del creditor'
            properties:
              FinancialInstitution:
                type: object
                description: 'Objeto que contiene la información de la institución financiera'
                properties:
                  Identification:
                    type: string
                    description: 'Código de la Entidad Receptora'
                    example: '250000'   
          Creditor:
            type: object
            description: 'Objeto que representa al creditor quien recibe el dinero'
            properties:
              CreditCard:
                type: string
                description: 'Código de Tarjeta de Crédito del Cliente'
                example: '123456789'
              Location:
                type: object
                description: 'Objeto que contiene la información de la dirección del creditor'
                properties:
                  Address:
                    type: string
                    description: 'Dirección del Cliente Receptor'
                    example: 'Dirección'
              Contact:
                type: object
                description: 'Objeto que contiene la información de la dirección del teléfono'
                properties:
                  PhoneNumber:
                    type: string
                    description: 'Número de teléfono fijo del Cliente Receptor'
                    example: '97145847'
                  MobileNumber:
                    type: string
                    description: 'Número de celular del Cliente Receptor'
                    example: '858885474'
              Account:
                type: object
                description: 'Objeto que contiene la información de la dirección de la cuenta del creditor'
                properties:
                  CCIIdentification:
                    type: string
                    description: 'Código de Cuenta Interbancario del Cliente Receptor '
                    example: '123456789'
          Transaction:
            type: object
            description: 'Objeto que representa a la información de la transacción'
            properties:
              Type:
                type: string
                description: 'Código de Transacción Extendida'
                example: 'M'
              ProxyValue:
                type: string
                description: 'Dato específico para MPP que se utilizará en actualizaciones futuras'
                example: 'M'
              ProxyType:
                type: string
                description: 'Dato específico para MPP que se utilizará en actualizaciones futuras'
                example: 'M'
              Channel:
                type: object
                description: 'Objeto que contiene la información del canal'
                properties:
                  ChannelReference:
                    type: string
                    description: 'Identificación del canal'
                    example: '11'
              CurrencyDetails:
                type: object
                description: Objeto que contiene la información de la moneda
                properties:
                  CurrencyInternalIdentifier:
                    type: integer
                    description: Identificador interno de moneda de CLA
                    example: 1
  RESPONSE_RetrieveExternalTransfersResponse:
    description: ''
    required:
      - RetrieveExternalTransfersResponse
    type: object
    properties:
      RetrieveExternalTransfersResponse:
        description: 'Objeto que representa al cuerpo de mensaje de respuesta'
        properties:
          Transaction:
            type: object
            description: 'Objeto que representa a la información de la transacción'
            properties:
              CreationDate:
                type: string
                description: 'A Fecha Local de la transacción'
                example: '16052024'
              CreationTime:
                type: string
                description: 'Hora Local de la transacción'
                example: '120000'
              TerminalId:
                type: string
                description: 'Código de identificación de terminal'
                example: '1'
              RetrievalReferenteNumber:
                type: string
                description: 'Número de referencia'
                example: '2024'                
              InstructionIdentification:
                type: string
                description: 'Autogenerado de identificación única de transacción'
                example: '1'                
              ResponseCode:
                type: string
                description: 'Código de Respuesta'
                example: '100'                
              ReasonCode:
                type: string
                description: 'Hace referencia a la fecha de liquidación'
                example: '100'
              SameCustomerFlag:
                type: string
                description: 'Indicador de Mismo Cliente, usado para determinar afectación de ITF'
                example: '1'
              ProxyValue:
                type: string
                description: 'Dato específico para MPP que se utilizará en actualizaciones futuras'
                example: 'M'
              ProxyType:
                type: string
                description: 'Dato específico para MPP que se utilizará en actualizaciones futuras'
                example: 'M'
          Creditor:
            type: object
            description: 'Objeto que representa al creditor quien recibe el dinero'
            properties:
              CreditCard:
                type: string
                description: 'Código de Tarjeta de Crédito del Cliente'
                example: '123456789'
              PartyIdentification:
                type: object
                description: 'Objeto que contiene la información del creditor'
                properties:
                  Name:
                    type: string
                    description: 'Nombre del Cliente Originante'
                    example: 'Jane Doe'
                  Code:
                    type: string
                    description: 'Tipo de Documento del Cliente Originante'
                    example: '1'
                  Identification:
                    type: string
                    description: ' Número de Documento del Cliente Originante'
                    example: 'Jhon Doe'
              PhoneAddress:
                type: object
                description: 'Objeto que contiene la información del teléfono'
                properties:
                  PhoneNumber:
                    type: string
                    description: 'Número de teléfono fijo del Cliente Originante'
                    example: '97145847'
                  MobileNumber:
                    type: string
                    description: 'Número de celular del Cliente Originante'
                    example: '858885474'
              Address:
                type: object
                description: 'Dirección del Cliente'
                properties:
                  AddressLine:
                    type: string
                    description: 'Dirección del Cliente Originante'
                    example: 'Dirección'
              BankAccounts:
                type: array
                description: 'Arreglo de objetos que contienen la información de las cuentas de ahorro'
                items:
                  type: object
                  properties:
                    AccountIdentification:
                      type: string
                      description: 'Número de identificación de la cuenta de ahorros'
                      example: '12345678901234'
                    CCIIdentification:
                      type: string
                      description: 'Código de Cuenta Interbancario (CCI)'
                      example: '00212345678901234567'
                    ProductIdentification:
                      type: integer
                      description: 'Identificador del producto'
                      example: 2

  REQUEST_RetrieveContactSweep:
    type: object
    properties:
      RetrieveContactSweep:
        type: object
        properties:
          DebtorAgent:
            type: object
            properties:
              FinancialInstitution:
                type: object
                properties:
                  Identification:
                    type: string
                    description: Código de la Entidad Originante
                    example: "0881"
          MessageIdentification:
            type: object            
            properties:
              CCEHash:
                example: "09876543-21ab-43de-85cd-9876543210ab"
                description: Identificador de la traza
                type: string 
          Contact:
            type: object
            properties:
              CustomerPhoneNumber:
                type: string
                description: Número de teléfono del Cliente (Valor Dummy) 
                example: "+51999999999"
          ContactList:
            type: array
            description: Directorio de contactos del cliente
            items:
              type: string
            example:
              - "+519521454477"
              - "+519876543210"
              - "+519998887770"
  RESPONSE_RetrieveContactSweepResponse:
    type: object
    properties:
      RetrieveContactSweepResponse:
        type: array
        items:
          type: object
          properties:
            ContactList:
              type: array
              items:
                type: object
                properties:
                  Contact:
                    type: object
                    properties:
                      PhoneNumber:
                        type: string
                        description: Número de celular
                        example: "+519521454477"
                  BankingServiceDetails:
                    type: array
                    description: Lista de directorios y códigos de entidad
                    items:
                      type: object
                      properties:
                        DirectoryCode:
                              type: string
                              description: Código de directorio
                              example: 0901
                        CreditorAgent:
                          type: object
                          properties:
                            FinancialInstitution:
                              type: object
                              properties:
                                Identification:
                                  type: string
                                  description: Código de la Entidad Originante
                                  example: "0555"