swagger: "2.0"
info:
  title: party-reference-data-directory-s
  version: 1.0.0
  description: Esta API permite obtener datos de la cuenta del cliente y detalles del dispositivo.
basePath: /party-reference-data-directory-s/v1
paths:
  /customer-and-device-contact/retrieve:
    get:
      tags:
        - BQ - CustomerAndDeviceInfo
      operationId: getCustomerAndDeviceInfo
      description: Obtener datos de la cuenta del cliente y detalles del dispositivo.
      summary: Obtener datos de la cuenta del cliente y detalles del dispositivo.
      produces:
        - application/json
      parameters:
        - name: accountIdentification
          in: query
          description: Número de cuenta del cliente.
          required: true
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/RESPONSE_RetrieveCustomerAndDeviceInfoResponse"
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/errorResponse"
        "401":
          description: Unauthorized
          schema:
            $ref: "#/definitions/errorResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/errorResponse"
        "422":
          description: Unprocessable Content
          schema:
            $ref: "#/definitions/errorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/errorResponse"
        "502":
          description: Bad Gateway
          schema:
            $ref: "#/definitions/errorResponse"
        "504":
          description: Gateway Timeout
          schema:
            $ref: "#/definitions/errorResponse"
definitions:
  RESPONSE_RetrieveCustomerAndDeviceInfoResponse:
    description: "Objeto que contiene el cuerpo del mensaje de salida."
    required:
      - RetrieveCustomerAndDeviceInfoResponse
    type: object
    properties:
      RetrieveCustomerAndDeviceInfoResponse:
        description: Objeto que almacena el mensaje de solicitud.
        type: object
        properties:
          Contact:
            description: Objeto que almacena información de contacto relacionada al cliente.
            type: object
            properties:
              EmailAddress:
                description: Dirección de correo electrónico.
                type: string
              PhoneNumber:
                description: Colección de información que identifica un número de teléfono, según lo definido por los servicios de telecomunicaciones.
                type: string

  errorResponse:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status_code:
              type: string
              description: Código de error
            message:
              type: string
              description: Mensaje de error
