swagger: '2.0'
info:
  title: correspondence-s
  version: 1.0.0
  description: Esta API permite enviar un mensaje de correo electrónico a uno o varios destinatarios.
basePath: /correspondence-s/v1
paths:
  /outbound-correspondence/provide:
    post:
      tags:
        - BQ - OutboundCorrespondence
      description: Enviar un mensaje de correo electrónico a uno o varios destinatarios.
      summary: Enviar un mensaje de correo electrónico a uno o varios destinatarios.
      operationId: provideOutboundCorrespondence
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/REQUEST_ProvideOutboundCorrespondence'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RESPONSE_ProvideOutboundCorrespondenceResponse'
        '204':
          description: No Content
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/errorResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/errorResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/errorResponse'
        '422':
          description: Unprocessable Content
          schema:
            $ref: '#/definitions/errorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorResponse'
        '502':
          description: Bad Gateway
          schema:
            $ref: '#/definitions/errorResponse'
        '504':
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/errorResponse'
definitions:
  errorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            status_code:
              type: string
              description: Código de error
            message:
              type: string
              description: Mensaje de error
  REQUEST_ProvideOutboundCorrespondence:
    description: 'Objeto que contiene el cuerpo del mensaje de solicitud.'
    required:
      - ProvideOutboundCorrespondence
    type: object
    properties:
      ProvideOutboundCorrespondence:
        description: Objeto que almacena el mensaje de solicitud.
        type: object
        properties:
          Correspondence:
            type: object
            description: Objeto que representa el servicio de correspondencia utilizado para la renderización y transmisión de documentos a través de diferentes canales de comunicación.
            properties:
              EmailAddresses:
                type: array
                description: Lista de correos electrónicos de los destinatarios a los que se enviará la correspondencia.
                items:
                  type: string
                  example: "juan.perez@gmail.com"
              CarbonCopyEmails:
                type: array
                description: Lista de correos electrónicos de los destinatarios en copia (CC).
                items:
                  type: string
                example: 
                  - "maria.lopez@cajalosandes.com"
                  - "carlos.gomez@protecso.com"
                  - "luisa.morales@gmail.com"
              BlindCarbonCopyEmails:
                type: array
                description: Lista de correos electrónicos de los destinatarios en copia oculta (CCO).
                items:
                  type: string
                example: 
                  - "carlos.garcia@cajalosandes.com"
                  - "eduardo.soto@cajalosandes.com"
              CorrespondenceTemplate:
                type: string
                description: Plantilla utilizada para ensamblar correspondencia 
                example: "{ \"subject\":\"Bienvenido a Caja Los Andes\", \"name\":\"Ernesto\", \"message\": \"¡Bienvenido, Ernesto! Te damos la bienvenida a Caja Los Andes. Esperamos que disfrutes tu experiencia con nosotros.\" }"
              CorrespondenceTemplateReference:
                type: string
                description: Referencia a una plantilla utilizada para ensamblar correspondencia
                example: "Welcome Template"
              Attachments:
                type: array
                description: Lista de archivos adjuntos que se enviarán junto con la correspondencia.
                items:
                  type: object
                  properties:
                    FileName:
                      type: string
                      description: Nombre del archivo
                      example: Términos y condiciones
                    Format:
                      type: string
                      description: Formato del archivo
                      example: PDF
                    FileURL:
                      type: string
                      description: URL del archivo adjunto
                      example: www.tyc.losandes.pe/doc.pdf
  RESPONSE_ProvideOutboundCorrespondenceResponse:
    description: Objeto que contiene el cuerpo del mensaje de salida
    required:
      - ProvideOutboundCorrespondenceResponse
    type: object
    properties:
      ProvideOutboundCorrespondenceResponse:
        type: object
        description: Objeto que contiene los datos de respuesta para el registro de cuenta.
        properties:
          Transaction:
            type: object
            description: Objeto que contiene la información relacionada al registro de cuenta
            properties:
              TransactionIdentification:
                type: integer
                description: Un identificador que permite hacer referencia de forma única a una instancia de una transacción.
                example: 112
